recipe_sha: 89985a79d8167c67516f03e61306c6096b95b73b86b3587900b27b21357961c0  # The commit at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
reason: |-
  fastq_io.h:30:10: fatal error: zlib.h: No such file or directory
category: |-
  compiler error
log: |-
  13:29:51 BIOCONDA INFO (OUT) $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++ -std=gnu++11 -O3 -pthread -DNDEBUG  -c demultiplex.cc
  13:29:51 BIOCONDA INFO (OUT) In file included from demultiplex.h:31,
  13:29:51 BIOCONDA INFO (OUT)                  from demultiplex.cc:29:
  13:29:51 BIOCONDA INFO (OUT) fastq_io.h:30:10: fatal error: zlib.h: No such file or directory
  13:29:51 BIOCONDA INFO (OUT)    30 | #include <zlib.h>
  13:29:51 BIOCONDA INFO (OUT)       |          ^~~~~~~~
  13:29:51 BIOCONDA INFO (OUT) compilation terminated.
  13:29:51 BIOCONDA INFO (OUT) make[1]: *** [Makefile:46: demultiplex.o] Error 1
  13:29:51 BIOCONDA INFO (OUT) make[1]: Leaving directory '$SRC_DIR/src/adapterremoval'
  13:29:51 BIOCONDA INFO (OUT) make: *** [Makefile:10: all] Error 2
  13:29:51 BIOCONDA INFO (OUT) ERROR: compilation failed for package ‘Rbowtie2’
  13:29:51 BIOCONDA INFO (OUT) * removing ‘/opt/conda/conda-bld/bioconductor-rbowtie2_1702041980598/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/R/library/Rbowtie2’
  13:29:51 BIOCONDA INFO (OUT) Traceback (most recent call last):
  13:29:51 BIOCONDA INFO (OUT)   File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
  13:29:51 BIOCONDA INFO (OUT)     sys.exit(main())
  13:29:51 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 256, in main
  13:29:51 BIOCONDA INFO (OUT)     call_conda_build(action, config)
  13:29:51 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
  13:29:51 BIOCONDA INFO (OUT)     result = api.build(
  13:29:51 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
  13:29:51 BIOCONDA INFO (OUT)     return build_tree(
  13:29:51 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3078, in build_tree
  13:29:51 BIOCONDA INFO (OUT)     packages_from_this = build(metadata, stats,
  13:29:51 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2198, in build
  13:29:51 BIOCONDA INFO (OUT)     utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  13:29:51 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 451, in check_call_env
  13:29:51 BIOCONDA INFO (OUT)     return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  13:29:51 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 427, in _func_defaulting_env_to_os_environ
  13:29:51 BIOCONDA INFO (OUT)     raise subprocess.CalledProcessError(proc.returncode, _args)
  13:29:51 BIOCONDA INFO (OUT) subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-rbowtie2_1702041980598/work/conda_build.sh']' returned non-zero exit status 1.
  13:30:01 BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmpo76vfx_h/build_script.bash:/opt/build_script.bash -v /opt/mambaforge/envs/bioconda/conda-bld/:/opt/host-conda-bld -v /home/runner/work/bioconda-recipes/bioconda-recipes/recipes/bioconductor-rbowtie2:/opt/recipe -e LANG=C.UTF-8 -e HOST_USER_ID=1001 quay.io/bioconda/bioconda-utils-build-env-cos7:2.11.0 /bin/bash /opt/build_script.bash
